CREATE DATABASE PROVA;

USE PROVA;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLI_NUM INT PRIMARY KEY NOT NULL,
CLI_NOME VARCHAR(30) NOT NULL,
CLI_RUA VARCHAR(40) NOT NULL,
CLI_NUMRUA INT,
CLI_BAIRRO VARCHAR(40) NOT NULL,
CLI_CIDADE VARCHAR(30) NOT NULL,
CLI_ESTADO VARCHAR(30) NOT NULL,
CLI_PAIS VARCHAR(30) NOT NULL,
CLI_CODPOSTAL VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS CARROS(
CAR_REGISTRO INT PRIMARY KEY NOT NULL,
CAR_MARCAR VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS APOLICE(
APO_NUM INT PRIMARY KEY NOT NULL,
APO_MARCA VARCHAR(30) NOT NULL,
APO_CLI INT NOT NULL,
APO_CAR INT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY (APO_CLI) REFERENCES CLIENTES (CLI_NUM),
CONSTRAINT FK_CARROS FOREIGN KEY (APO_CAR) REFERENCES CARROS (CAR_REGISTRO)
);

CREATE TABLE IF NOT EXISTS ACIDENTES(
ACI_DATA DATE NOT NULL,
ACI_HORA TIME NOT NULL,
ACI_LOCAL TEXT NOT NULL,
ACI_CAR INT PRIMARY KEY NOT NULL,
CONSTRAINT FK_CARROS FOREIGN KEY (ACI_CAR) REFERENCES CARROS (CAR_REGISTRO)
);

CREATE TABLE IF NOT EXISTS CLIENTES_CARROS(
CLCR_CLIENTES INT NOT NULL,
CLCR_CARROS INT NOT NULL,
PRIMARY KEY (CLIENTE_CARROS),
CONSTRAINT CLCR_FK_CLIENTES FOREIGN KEY (CLCR_CLIENTES) REFERENCES CLIENTES(CLI_COD),
CONSTRAINT CLCR_FK_CARROS FOREIGN KEY (CLCR_CARROS) REFERENCES CARROS(CAR_REGISTRO)
);
